language: minimal

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then sudo add-apt-repository ppa:ansible/bubblewrap -y && sudo apt-get update ;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then sudo apt-get install bubblewrap ; fi
  - yes /usr/local/bin | sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)

before_script:
  - opam init -a
  - eval $(opam env)
  - opam install dune odoc -y

script:
  - dune build @install
  - dune build @runtest
  - dune build @doc
  - dune install
